### ISSUE TITLE
在计算loss的时候报cuda错误

### ISSUE THREAD

**Issue by zzf-damon** [foundation-multimodal-models/CAL#4]
如题：
我在一个 internvl1.5的代码上进行开发。

![image](https://github.com/foundation-multimodal-models/CAL/assets/56286786/895366ef-410f-48ce-adba-873e116b1532)

代码执行到红框报如下错误。

 ../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [0,0,0], thread: [0,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [0,0,0], thread: [1,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [0,0,0], thread: [2,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [0,0,0], thread: [3,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [0,0,0], thread: [4,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [0,0,0../aten/src/ATen/native/cuda/ScatterGatherKernel.cu], thread: [5:144,0: operator(),0: block: [0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds",0` failed.

没有头绪解决这个问题，作者有什么建议吗？

**Comment by Menoly-xin** [comment]
We have set the image token index to -200, so when calculating the loss, you need to convert it to -100.

If you need any further assistance, feel free to ask!
